# Generated by Django 5.1.2 on 2025-01-08 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_slug_alter_printedissue_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.CreateModel(
            name='HomepageStorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_articles', models.ManyToManyField(help_text='Select up to 4 articles to feature on the homepage', limit_choices_to={'is_published': True}, related_name='featured_articles', to='articles.article')),
                ('featured_editorial', models.OneToOneField(help_text='Select the editorial to feature on the homepage', limit_choices_to={'category__name': 'Editorial', 'is_published': True}, on_delete=django.db.models.deletion.CASCADE, related_name='featured_editorial', to='articles.article')),
                ('featured_feature', models.OneToOneField(help_text='Select the feature article to display on the homepage', limit_choices_to={'category__name': 'Feature', 'is_published': True}, on_delete=django.db.models.deletion.CASCADE, related_name='featured_feature', to='articles.article')),
                ('top_story', models.OneToOneField(help_text='Select the top story to feature on the homepage', limit_choices_to={'is_published': True}, on_delete=django.db.models.deletion.CASCADE, related_name='top_story', to='articles.article')),
            ],
            options={
                'verbose_name': 'Homepage Story',
                'verbose_name_plural': 'Homepage Stories',
            },
        ),
    ]
