# Generated by Django 5.1.2 on 2025-01-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_category_categorie_rename_articles_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagestorie',
            name='featured_editorial',
            field=models.OneToOneField(help_text='Select the editorial to feature on the homepage', limit_choices_to={'category__id': 2, 'is_published': True}, on_delete=django.db.models.deletion.CASCADE, related_name='featured_editorial', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='homepagestorie',
            name='featured_feature',
            field=models.OneToOneField(help_text='Select the feature article to display on the homepage', limit_choices_to={'category__id': 3, 'is_published': True}, on_delete=django.db.models.deletion.CASCADE, related_name='featured_feature', to='articles.article'),
        ),
    ]
