# Generated by Django 5.1.2 on 2025-01-01 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintedIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('volume', models.PositiveIntegerField()),
                ('issue_no', models.PositiveIntegerField()),
                ('month_range', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='printed_issues_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'unique_together': {('volume', 'issue_no')},
            },
        ),
    ]
